(()=>{
const products=window.CHOCOSCENT_PRODUCTS||[],shop=document.getElementById('shop');if(!shop||!products.length)return;
const section=document.createElement('section');section.id='fragrance-catalogue';section.className='catalogue-section';
section.innerHTML='<div class="catalogue-heading"><p class="eyebrow">L’ORIENTALE FRAGRANCES</p><h2>Find your signature scent.</h2><p>Explore all 57 fragrances across 10 collections. Discover their character, ingredients, and original product photography.</p></div><div class="catalogue-controls"><input id="fragrance-search" type="search" placeholder="Search a fragrance or note…" aria-label="Search fragrances and notes"><select id="fragrance-filter" aria-label="Filter fragrance collection"><option value="">All collections</option></select><select id="scent-filter" aria-label="Filter scent family"><option value="">All scent families</option></select></div><p id="catalogue-count" class="catalogue-count" role="status" aria-live="polite"></p><div id="fragrance-grid" class="fragrance-grid"></div><p class="catalogue-footnote">Prices and availability on request.</p>';
shop.after(section);
const filter=section.querySelector('#fragrance-filter'),family=section.querySelector('#scent-filter'),search=section.querySelector('#fragrance-search'),grid=section.querySelector('#fragrance-grid'),counter=section.querySelector('#catalogue-count');
function option(select,name,label=name){const o=document.createElement('option');o.value=name;o.textContent=label;select.append(o)}
for(const name of new Set(products.map(p=>p.collection)))option(filter,name,name+' ('+products.filter(p=>p.collection===name).length+')');
for(const name of [...new Set(products.map(p=>p.family).filter(Boolean))].sort())option(family,name);
const dialog=document.createElement('dialog');dialog.className='fragrance-dialog';dialog.setAttribute('aria-labelledby','fragrance-title');dialog.innerHTML='<div class="cart-head"><p class="eyebrow">DISCOVER YOUR FRAGRANCE</p><button class="fragrance-close" aria-label="Close fragrance details">✕</button></div><div class="fragrance-detail-content"></div>';document.body.append(dialog);
let returnFocus=null;const close=dialog.querySelector('.fragrance-close');close.addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.style.overflow='';if(returnFocus?.isConnected)returnFocus.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function node(tag,text,className){const e=document.createElement(tag);if(text)e.textContent=text;if(className)e.className=className;return e}
function picture(p,lazy=true){const img=node('img');img.src=p.image;img.alt=p.name+' perfume bottle, '+p.collection+' collection';img.loading=lazy?'lazy':'eager';img.decoding='async';img.width=400;img.height=400;return img}
function showProduct(p,button){returnFocus=button;const content=dialog.querySelector('.fragrance-detail-content');content.replaceChildren();const imageArea=node('div',null,'fragrance-detail-image');imageArea.append(picture(p,false));const info=node('div',null,'fragrance-detail-info');const title=node('h2',p.name);title.id='fragrance-title';info.append(node('p',p.collection+' collection','eyebrow'),title,node('p',p.volume+' · '+p.concentration,'fragrance-spec'),node('p',p.description,'fragrance-description'));
const list=node('dl',null,'fragrance-notes');for(const [label,value]of [['Scent family',p.family],['Top notes',p.topNotes],['Heart notes',p.heartNotes],['Base notes',p.baseNotes],['Accords',p.accords]])if(value){list.append(node('dt',label),node('dd',value))}info.append(list,node('p','Prices and availability on request.','fragrance-availability'));content.append(imageArea,info);dialog.showModal();document.body.style.overflow='hidden';close.focus()}
function render(){const term=search.value.trim().toLocaleLowerCase();const matching=products.filter(p=>(!filter.value||p.collection===filter.value)&&(!family.value||p.family===family.value)&&(!term||[p.name,p.collection,p.family,p.topNotes,p.heartNotes,p.baseNotes].join(' ').toLocaleLowerCase().includes(term)));counter.textContent=matching.length+' of '+products.length+' fragrances';grid.replaceChildren();const fragment=document.createDocumentFragment();for(const p of matching){const card=node('article',null,'fragrance-card');const visual=node('button',null,'fragrance-visual');visual.type='button';visual.setAttribute('aria-label','View '+p.name+' fragrance details');visual.append(picture(p));visual.addEventListener('click',()=>showProduct(p,visual));const info=node('div',null,'fragrance-info');const details=node('button','View fragrance ↗','fragrance-details-button');details.type='button';details.addEventListener('click',()=>showProduct(p,details));info.append(node('small',p.collection+' collection'),node('h3',p.name),node('p',p.volume+' · '+p.concentration),node('p',p.family,'fragrance-family'),details);card.append(visual,info);fragment.append(card)}if(!matching.length){const empty=node('div',null,'catalogue-empty');empty.append(node('h3','No fragrances found'),node('p','Try another name, note, or collection.'));const reset=node('button','Clear filters','btn');reset.addEventListener('click',()=>{search.value='';filter.value='';family.value='';render();search.focus()});empty.append(reset);fragment.append(empty)}grid.append(fragment)}
filter.addEventListener('change',render);family.addEventListener('change',render);search.addEventListener('input',render);render();
})();

